version: "3.7"
services:
  app:
    build:
      args:
        user: josefo
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: travellist
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - travellist

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 4055:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - travellist

networks:
  travellist:
    driver: bridge
